name: CD-to-DockerHub
on:
  push:
    branches: [ main ]

jobs:
  dockerhub-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push image
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/python-app
        docker build -t $IMAGE:latest .
        docker push $IMAGE:latest

    - name: Create timestamp
      run: echo "TS=$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_ENV

    - name: Tag image with timestamp and push
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/python-app
        docker tag $IMAGE:latest $IMAGE:$TS
        docker push $IMAGE:$TS